#!/usr/bin/env bash

# 変数

view="[$0]:"


# GUI関数

# error_window
error_window () {
    zenity \
    --error \
    --width 350 \
    --title $0 \
    --text "${1}"
    exit 0
}

#info_window
info_window() {
    zenity \
    --info \
    --width 350 \
    --title $0 \
    --text "${1}"
    exit 0
}

#ques_window
ques_window() {
    zenity \
    --question \
    --width 350 \
    --title $0 \
    --text "${1}"
}

# デスクトップ環境選択ウィンドウ
de_select() {
    zenity \
    --list \
    --title $0 \
    --text "デスクトップ環境を選択..." \
    --column "デスクトップ環境" GNOME KDE Cinnamon MATE Xfce LXDE LXQt DDE

}

# インストール/アンインストール処理
install_proc () {
    # $1 -> ["install"] or ["uninstall"]
    # $2 -> [DE Name]
    # $3 -> [install/uninstall cmd]
    if [ $1 = "install" ]; then
        ques_window "${2}をインストールしますか？"

        question=$?
        case $question in
            0)
                # インストール処理
                $3 || error_print "インストールに失敗しました。"
                sudo apt-get update -y
                sudo apt-get upgrade -y
                ok_print "インストール処理が完了しました。"
                info_window "インストールが完了しました。"
            ;;
            *)
                :
            ;;
        esac


    elif [ $1 = "uninstall" ]; then
        ques_window "${2}をアンインストールしますか？"

        question=$?
        case $question in
            0)
                # アンインストール処理
                $3 || error_print "アンインストールに失敗しました。"
                sudo apt-get autoremove -y
                ok_print "アンインストール処理が完了しました。"
                info_window "アンインストールが完了しました。"
            ;;
            *)
                :
            ;;
        esac


    else
        error_print "例外が発生しました。"
    fi
}


# CUI関数

# エラー出力関数
error_print () {
    printf "${view} \033[31m${1}\033[m\n"
    error_window "${1}"
}

# OK出力関数
ok_print () {
    printf "${view} \033[32m${1}\033[m\n"
}

# 処理の呼び出し
call () {
    bash $0
}



# ----------------------------------------------------------- #

# パスワード入力のGUI化（pkexec）
if [ ! $UID = 0 ]; then
    pkexec env DISPLAY=$DISPLAY XAUTHORITY=$XAUTHORITY $0
    exit 0
fi

# 現在のデスクトップ環境を取得

# メインメニュー
select=$(
    zenity \
    --title $0 \
    --info \
    --text "何を実行しますか?" \
    --ok-label="終了" \
    --extra-button="インストール" \
    --extra-button="アンインストール" \

)

mainmenu=$?

case $mainmenu in
    0)
        exit 0
    ;;
    *)
        :
    ;;
esac

case $select in
    "インストール")
        #デスクトップ環境選択ウィンドウ
        install=$(de_select)

        menu=$?
        case $mainmenu in
            0)
                :
            ;;
            *)
                case $install in
                    GNOME)
                        install_proc "install" "GNOME" ":"

                    ;;
                    KDE)
                        


                    ;;
                    Cinnamon)
                        


                    ;;
                    MATE)
                        


                    ;;
                    Xfce)
                        


                    ;;
                    LXDE)
                        

                    ;;
                    LXQt)



                    ;;
                    DDE)


                    ;;
                    *)
                        error_print "Error. Exception occured."

                    ;;
                esac

            ;;
        esac

    ;;
    "アンインストール")
        #デスクトップ環境選択ウィンドウ
        uninstall=$(de_select)

        menu=$?
        case $mainmenu in
            0)
                :
            ;;
            *)
                case $uninstall in
                    GNOME)
                        

                    ;;
                    KDE)
                        


                    ;;
                    Cinnamon)
                        


                    ;;
                    MATE)
                        


                    ;;
                    Xfce)
                        


                    ;;
                    LXDE)
                        

                    ;;
                    LXQt)



                    ;;
                    DDE)


                    ;;
                    *)
                        error_print "Error. Exception occured."

                    ;;
                esac

            ;;
        esac
    ;;
    *)
        error_print "Error. Exception occured."
    ;;
esac

call